### ISSUE TITLE
Dragon Armor Rendering Incorrect Textures

### ISSUE THREAD

**Issue by EvilDylan** [ArkTechMC/IAF-Patcher#2]
Mod Loader: Forge 47.3.4
Ice and Fire Version: 2.1.13
Mod Version: 0.1.1
Game Version: 1.20.1

Description: When Ice and Fire Patcher is installed, the dragon armor renders incorrectly. Iron armor has no texture and paints the dragon black and magenta, silver armor has diamond armor textures, diamond armor has gold armor textures, gold armor has ice dragonsteel textures, etc. This does not occur without Ice And Fire Patcher installed.

Steps to Reproduce:
1. Install Citadel, Ice and Fire: Dragons, and Ice And Fire Patcher on a Forge instance.
2. Acquire a tame dragon.
3. Equip the tame dragon with armor of choice; Diamond or Iron preferred for contrast.
4. Disable IAF Patcher and reload the game to demonstrate the issue does not occur in base IaF.

**Comment by IAFEnvoy** [comment]
This fix removed. Unnecessary fix and cause bugs
